[package]
name = "xremap"
version = "0.7.5"
edition = "2021"
description = "Dynamic key remapp for X and Wayland"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.59"
clap = { version = "3.2.16", features = ["derive"] }
clap_complete = "3.2.3"
derive-where = "1.0.0"
env_logger = "0.9.0"
evdev = "0.12.0"
indoc = "1.0"
lazy_static = "1.4.0"
log = "0.4.17"
nix = "0.24.2"
regex = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "2.0", features = ["chrono"] }
serde_yaml = "0.9"
swayipc = { version = "3.0.0", optional = true }
x11rb = { version = "0.10.1", optional = true }
zbus = { version = "1.9.2", optional = true }

[features]
gnome = ["zbus"]
sway = ["swayipc"]
x11 = ["x11rb"]
